# site settings
title: Home
#subtitle: by HTML5 UP
email: pranitarsharma@gmail.com,prsharma@ncsu.edu
description: M.S. in Computer Science <br /> Actively looking for Summer Internships
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 3002 Kings Court
city: Raleigh
state: NC
zip_code: 27606
country: United States of America
phone: (984) 218-8069

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://github.com/pranita-s
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/pranita-s
pinterest_url: https://in.pinterest.com/pranitarsharma/
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
